### ISSUE TITLE
CVUSA ground image orientation

### ISSUE THREAD

**Issue by Sinnaeve** [Liumouliu/OriCNN#1]
Hi,

I'm trying to replicate your experiment on the CVUSA dataset, are the ground view panorama always oriented to the north in this dataset ? It's what I understand from your code as batch_grd_yawpitch[i,:,:,0] seems to be the same for every pictures, but I couldn't find an external source confirming it.

Thank you

**Comment by Liumouliu** [comment]
Yes, they are always oriented to the north in this dataset.
You can confirm it by verifying ground-view and satellite image pairs.
Also see section 3.2 in this paper: Predicting Ground-Level Scene Layout from Aerial Imagery.
PS: the best way to reach me is sending me an email, not by issues.
